### PR TITLE
Add GitHub Actions workflow for automating Docker Image building

### PR DESCRIPTION
**Pull request by pholawat-tle**
This is for Issue #57.

Create docker-image.yml to automate building and pushing docker images to Docker Hub after a release has been published on GitHub.

Secret variable DOCKER_PASSWORD and DOCKER_USERNAME must be add to the repo for this to work.

### CODE REVIEW

**Comment by TannerGabriel** [comment]
Looks good. Maybe consider adding a timeout to the action using the `timeout-minutes` parameter to prevent a stuck container from consuming unneeded CI/CD time and resources.

**Comment by TannerGabriel** [comment]
@souramoo Is the Dockerhub account used in the code your account or that of someone related to the repository so we could get the Dockerhub credentials as Github secrets.

**Comment by souramoo** [comment]
Thanks for this, and looks largely good to me! Alas @Caroga controls the dockerhub account, will need to coordinate with him to automate deployment or if he is busy I'm happy to make a new one myself :)

**Comment by Caroga** [comment]
Hi there, I am more than happy to provide access. You can send me a message and we can get this pipeline connected.

**Comment by TannerGabriel** [comment]
@Caroga thank you for offering to host the image. I believe that @souramoo is the only one with the permissions needed to add such credentials to the repository. Therefore it would be great if you coordinate adding the credentials with him.

**Comment by Caroga** [comment]
Hi @souramoo , @TannerGabriel , I just wanted to check in that I added @souramoo as a maintainer to the docker hub repo. You should be able to use your own deployment keys. 
Please let me know if anything else is needed.

**Comment by TannerGabriel** [comment]
@souramoo Great that this is merged now. Maybe we could also make a new release with all the changes from the last months.

**Pull request merged**
