### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by mschmidtkorth**

### CODE REVIEW

**Review by mschmidtkorth — COMMENTED** [review]
Fixed translation

**Comment by souramoo** [comment]
Thanks for this contribution! :) Merging now!

**Review by mschmidtkorth — COMMENTED** [review]
Updated translation

**Comment by mschmidtkorth** [comment]
Thanks for merging @souramoo! By the way, the "Upvotes/Newest/Oldest" sorting methods do not seem to be translateable.

**Comment by souramoo** [comment]
Whoops, that's totally my bad! (I think) I've fixed the problem with commit 8e1c4bb - i18n is a relatively new feature, thanks for battle-testing it!

**Pull request merged**
