### PR TITLE
Add docker specific instructions

### PR DESCRIPTION
**Pull request by Caroga**
As a result of switching from Commento to Commento++ for the time being I've setup a small pipeline that will create Commento++ docker images.
They can be found on gitlab and hub.docker.com, they are mirrored.

I've added this to the documentation as I thought this repo would benefit from this.

**Links**
- https://hub.docker.com/r/caroga/commentoplusplus
- https://gitlab.com/caroga/commentoplusplus-docker

### CODE REVIEW

**Comment by souramoo** [comment]
Thanks Roberto! Looks good to me 👍🏽 

I might end up merging the docker image building with the CircleCI integration I have in this repo at some later date just to streamline the new release deployment process but I think this is great!

**Comment by Caroga** [comment]
Great, thanks for merging!
Yeah I hope eventually all your work could be merged upstream. I don't expect my pipeline to have a long life, I just needed the images containing the patched commento version.
Anyways, thanks again!

**Comment by souramoo** [comment]
No worries! I hope so too, if the original author becomes active again I have a lot more merge requests with improvements ready for him!

**Comment by WyriHaximus** [comment]
Hey @souramoo, @Caroga has been keeping me up to date with his efforts to contact the original author. For my own usage of commento I maintain a Helm chart over at https://github.com/WyriHaximusNet/helm-charts/tree/master/charts/commento for using with Kubernetes. Does your fork container any database migrations? Considering (temporary) switching to @Caroga's image and have all the sweet new features I've been missing. But I don't want to risk database issues because of migrations when potentially switching back to the official image.

**Comment by souramoo** [comment]
Hey! I've added one migration at https://github.com/souramoo/commentoplusplus/blob/master/db/20200730134007-comment-count-update.sql - this is to fix the comment counting bug in the original repo when deleting comments, but it doesn't do anything major (just recounts all the comments and adds back in the trigger function when comments are deleted).

You should be able to switch back and forth without any database issues!

**Comment by WyriHaximus** [comment]
Thank you @souramoo, that looks safe to me indeed :+1: ! Will look into trying out commento++ soon :tada: .

**Pull request merged**
